### ISSUE TITLE
Content Review

### ISSUE THREAD

**Issue by proubatsis** [OpenLiberty/draft-guide-arquillian-managed#2]
**What you'll learn?**

* I'll be learning about Arquillian, but why do I want to learn about it? What is it and why should I be interested?

**Try what you’ll build**

* Gradle did not work for me

![image](https://user-images.githubusercontent.com/8409464/42340745-d4646980-805e-11e8-8f54-59979849fc6c.png)

**Configuring your test build**

* We don't typically use partial files, we provide the entire file in our other guides

**Configuring the server.xml**

* We don't typically use partial files, we provide the entire file in our other guides

**Adding your Arquillian test**

* The `src/test/java/org/arquillian/example` directory should exist in the `start` directory

**Running the tests**

* Sample test output is not shown in the guide

**Other**

* Acrolink score of 61 (minimum 70 is required): https://ibm.acrolinx.cloud/output/en/README_adoc_50VJ5WHXBK_34998d1f5de25c38_249290444_report.html

@evelinec

**Comment by chyt** [comment]
> Try what you’ll build - Gradle did not work for me

Are you running on an older version Java 7? @evelinec is aware of an issue with Maven artifacts downloading on Java 7. They are working on a solution. 

> Running the tests - Sample test output is not shown in the guide

I do show some sample test output:

```
PhraseBuilder <init>
PhraseBuilder <init>
PhraseBuilder initialize
Hello, Earthling!
```

The reason I do not show the entire output is because it is very different depending on whether you are running Maven and Gradle. But the part that I reproduced above is common and it is the most important. The rest is just the JUnit and container setup. 

> Acrolink score of 61 (minimum 70 is required)

Have you looked at the issue breakdown? Much of it is trivial (saying that `there is` should be `there's` or just straight up wrong (`Open Liberty` should be `open Liberty`). While something like this is fine for catching spelling or grammatical issues, I don't think that there should be a score requirement when most of what it has identified are non-issues. 

I will resolve the other issues in commits to come.

**Comment by proubatsis** [comment]
@chyt

---

> Are you running on an older version of Java 7?
No I am running Java 8, the output of `java -version` for me is:
```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) Client VM (build 25.161-b12, mixed mode)
```
---

> I do show some sample test output:

Sorry, I was unclear. We typically show this output as well:

```
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 18.544 s - in org.arquillian.example.GreeterIT
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

---

**Acrolink**

I am not too sure how strict the policy on the minimum score of 70 is, can you give your view on this please @evelinec ?

**Comment by chyt** [comment]
> No I am running Java 8

@evelinec @Ahmad-Ayyoub Can you add Travis integration for this project so that we can see if this issue exists on Travis? I have not seen it.

> Sorry, I was unclear. We typically show this part of the output as well:

As I said before, we do not show that section of the output since it is specific to Maven. I do say that they should see a build success message though, indicating that the tests have passed. This is effectively the same thing.

**Comment by evelinec** [comment]
Re Acrolink, did you try fixing some of the issues raised and then re-run the check? @proubatsis or @chyt

**Comment by evelinec** [comment]
Re setting up automated test for this repo, we will arrange it. @chyt

**Comment by evelinec** [comment]
Where reasonably recommended by Acrolink and if they are fixed, it'd be good with the score. @proubatsis can you verify all the other items are fixed for this issue? Thanks.

**Comment by proubatsis** [comment]
@evelinec @chyt 
* Entire files should be provided, no partial files.
* This path does not exist `src/test/java/org/arquillian/example` in the start directory
* Gradle not working for me

**Comment by chyt** [comment]
Addressed these issues.

**Comment by evelinec** [comment]
@proubatsis can you review all the changes and follow up. Thank you.

**Comment by proubatsis** [comment]
All of the points have been fixed except for:
> Entire files should be provided, no partial files.

Here's a screenshot of what I mean for reference:
![image](https://user-images.githubusercontent.com/8409464/44919713-1b0f4b00-ad0c-11e8-9439-4c3c8342e6e3.png)

The entire pom file should be displayed in the guide rather than just snippets.

**Comment by evelinec** [comment]
All issues addressed.
