### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/draft-guide-arquillian-managed#30]
I reviewed the intro mainly (not the rest in detail). /cc @yeekangc 

I think the intro is trying to say too much without enough focus:

- [ ] " using the Arquillian Liberty Managed container and JUnit with Maven in Open Liberty" Should this be " using the Arquillian Liberty Managed container with JUnit and Maven in Open Liberty"? I was a bit confused about what JUnit was contributing because it says "and" as if JUnit was doing something equivalent to Arquillian. Yet, JUnit is there just to run the Arquillian tests, in the same way that Maven is there just to run the builds that run the tests, etc (ie JUnit and Maven are there to enable Arquillian tests). Also "in Open Liberty"? Or "on" or "with"?
- [x]  "Arquillian is a testing platform to develop automated functional, integration and acceptance tests for your Java applications." I wonder if this sentence could be moved to after the first sentence in the first paragraph? Then follow it with a sentence like "JUnit is used to run the Arquillian tests."
- [x] How about this for the first couple of paragraphs?

    "You will learn how to develop tests for your microservices using the Arquillian Liberty Managed container with JUnit and Maven in Open Liberty. Arquillian is a testing platform to develop automated functional, integration and acceptance tests for your Java applications. Arquillian sets up the test environment and is able to handle the application server life cycle for you, so you can focus on writing tests. In this guide, you will run the Arquillian tests using JUnit and Maven. The Liberty Maven plugin simplifies the process of managing Arquillian dependencies and setting up your Arquillian managed container in which the tests run.

    Arquillian tests look similar to common unit tests but an Arquillian test run from JUnit has three core components: @RunWith(Arquillian.class), @Deployment, and @Test. After setting up these three components, you have everything you need to test your microservices. You will learn more about these components in the test class."

- [x] The paragraph starting "Arquillian allows different application servers" - I'm not quite sure what it's trying to say. I think it's explaining about Arquillian managed containers? This needs to be clearer. I think the first sentence needs to define containers eg start with "Arquillian managed containers are...". maybe "Arquillian managed containers are application servers/runtimes that are running in the same JVM as the junit test."?
- [x] Then get rid of the sentence about "embedded, managed, remote..." because it's not helpful if you're not going to define them (and I don't think it's useful to define things that aren't relevant to this guide). 
- [x] Then the rest of the paragraph from "This guide uses the Arquillian Liberty Managed container, which is...".

Structure question:
- [x] Is it really necessary to do all the configuration before you can even start to write the Arquillian tests? Wouldn't it be possible to write the first test, then configure Arquillian to run in Liberty so that it can be run, then do the rest (or do you end up with loads of errors when writing the tests?)? Or some variant of this so that the reader doesn't have to go through loads of setup without getting to see anything working - chances are they're more interested in writing the tests than in setup.

Minor style comments (I didn't do a full review for style so it should still get an ID review):
- [x] "these three components setup" should be "...set up" (two words). Similarly "and setup the Liberty server.xml" should be "and set up the Liberty server.xml". ("setup" is a noun so should only be used after "the" or "a". The verb is "to set up".)
- [x] Avoid using future tense other than in the opening section. Don't start instruction sections with "You will need " and "You will start configuring" - there's no need. Instead "Configure your build..." and "Start by configuring your test build with Maven" (or whatever that sentence is meant to say - it's not currently grammatical....
- [x] "Bill of Materials" should be "Bill of Material" in Arquillian.

**Comment by evelinec** [comment]
Regarding this point: 
- [ ]  " using the Arquillian Liberty Managed container and JUnit with Maven in Open Liberty" Should this be " using the Arquillian Liberty Managed container with JUnit and Maven in Open Liberty"? I was a bit confused about what JUnit was contributing because it says "and" as if JUnit was doing something equivalent to Arquillian. Yet, JUnit is there just to run the Arquillian tests, in the same way that Maven is there just to run the builds that run the tests, etc (ie JUnit and Maven are there to enable Arquillian tests). Also "in Open Liberty"? Or "on" or "with"?
EC: I changed the "in Open Liberty" to "on Open Liberty". 

@chyt what do you think of the suggestion? I attempted to made some changes where appropriate in

**Comment by evelinec** [comment]
About the Structure question:

- [ ] Is it really necessary to do all the configuration before you can even start to write the Arquillian tests? Wouldn't it be possible to write the first test, then configure Arquillian to run in Liberty so that it can be run, then do the rest (or do you end up with loads of errors when writing the tests?)? Or some variant of this so that the reader doesn't have to go through loads of setup without getting to see anything working - chances are they're more interested in writing the tests than in setup.
EC: The setups are necessary for the Arquillian tests as these are adding the required dependencies and application runtime to enable developing the tests. It is possible to arrange the setups after the creating the tests in this guide, because the pom.xml is simply provided to user in the `start` directory.  Logically, the tests and the setups are needed side by side. So it doesn't matter which one goes first. The arquillian guides have some in both ways.

**Comment by evelinec** [comment]
@lauracowen can you review the changes in the latest test site?

**Comment by evelinec** [comment]
All of these feedback had been re-verified. Close issue.
