### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by andrewdes** [OpenLiberty/draft-guide-arquillian-managed#4]
**General**
* Description is basically just a mirror of the title
* Entire files should be used, not just partial code snippets
* Directory structure is incorrect. Visit Project Structure section in following wiki: https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles

**What you'll learn?**
* This section should be expanded. Perhaps include what Arquillian is and the advantages/importance that it has.

**Try what you'll build**
* Have the maven command and gradle command in 2 separate code blocks
* "This will be followed shortly by a message indicating a successful build." line might work better after the code block displaying the console output.
* Perhaps the "Hello, Earthling!" phrase could be modified to be more meaningful/relevent
* gradle build doesn't work for me (same issue as: https://github.com/OpenLiberty/draft-guide-arquillian-managed/issues/2)

**Configuring your test build**
* "You can learn more about the Arquillian Liberty dependency bundles _here_."  instead of hyperlinking here, hyperlink the title of where the link is taking users (Arquillian Liberty Dependencies repository.)

Likewise for the other 4 times it is used (twice more in using Maven section, 2 times in using gradle section)
* Is there a reason that the maven liberty plugin version is defined in the following way: "[17.0.0.4,)"? The other guides tend to use "RELEASE".

**Configuring the server.xml**
* Entire file should be placed here. Instead of telling the user to add a particular feature.

**Adding your Arquillian test**
* "Create the test file at src/test/java/org/arquillian/example/GreeterIT.java" -> "Create the src/test/java/org/arquillian/example/GreeterIT.java test file."
* "The contents of the file are reproduced below. A detailed explanation follows." Not sure if these sentences are actually necessary. 
* According to https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles, should have separate variables for expected and actual defined when using assertEquals() method.
* Test application isn't available at http://localhost:9080/test/ (I am assuming this is because the test application is automatically undeployed and server is shut down after the test. If the user has to visit the browser at a particular moment, I feel like this isn't a great experience for them).

**Comment by chyt** [comment]
```
"This will be followed shortly by a message indicating a successful build." line might work better after the code block displaying the console output.
```
As I've previously mentioned, I did not do this because console output is significantly different between Maven and Gradle.

```
Perhaps the "Hello, Earthling!" phrase could be modified to be more meaningful/relevent
```
This is basically a hello world Arquillian guide so I think the message is appropriate. 

```
Is there a reason that the maven liberty plugin version is defined in the following way: "[17.0.0.4,)"? The other guides tend to use "RELEASE".
```

Setting dependency version as `RELEASE` is not supported starting with Maven 3. The `assemblyArtifact` config binds to `ArtifactItem`, which is an internal Maven object so it seems like it still recognizes the `RELEASE` tag, but using version ranges is better practice.

```
Test application isn't available at http://localhost:9080/test/ (I am assuming this is because the test application is automatically undeployed and server is shut down after the test. If the user has to visit the browser at a particular moment, I feel like this isn't a great experience for them).
```
There is no purpose in viewing the test application, there are no endpoints. 

Will address remaining comments in an upcoming commit.

**Comment by andrewdes** [comment]
> "This will be followed shortly by a message indicating a successful build." line might work better after the code block displaying the console output.

Just to clarify what I meant by this issue, the guide currently has the following:


>Between the server start and stop messages, you will see the following console output indicating that your test has passed. This will be followed shortly by a message indicating a successful build.
```
PhraseBuilder <init>
PhraseBuilder <init>
PhraseBuilder initialize
Hello, Earthling!
```


Perhaps this would work better with something such as:

> Between the server start and stop messages, the following console output will be displayed, indicating that the test has passed.
```
PhraseBuilder <init>
PhraseBuilder <init>
PhraseBuilder initialize
Hello, Earthling!
```
> This output will be followed shortly by a message indicating a successful build.

This might be better to avoid confusion as to what is being displayed in the code block. The way it is currently written, it may be may be unclear as to whether the code block is the console output displaying that the test has passed or the message indicating a successful build.

&

The guide instructs the users to run a `mvn clean install` then says: 
> In either case, you will notice that the server is created and started, with a test application built from your ShrinkWrap archive that is deployed and available at http://localhost:9080/test/.

So if there is no purpose in viewing the test application, there isn't really a point in directing users to the test application.

**Comment by chyt** [comment]
Ok I see, I will reword the first point. As to the second point, I'm not really directing the users to the app, instead I want them to confirm that they see that an application has started at that endpoint from the console.

**Comment by andrewdes** [comment]
Oh alright, I understand now. The way I interpreted the sentence was that the test application is available at `http://localhost:9080/test/` so I clicked the link, only to be lead to "This site can't be reached." 

Perhaps this sentence could be reworded in such a way that it avoids confusion. I am worried that people  may read that the application is deployed and available and try to follow the link provided.

**Comment by chyt** [comment]
Regarding the second point, I changed the phrase `deployed and available` to just `deployed`. Maybe this will be less encouraging to the user to actually go and visit that endpoint? Not sure how else to rephrase this without explicitly telling them *not* to visit the endpoint, which sounds kind of weird.

**Comment by justineechen** [comment]
I looked over the feedback you addressed and changed the rest into check boxes so the changes can be tracked easily.

**General**

- [ ]  Description is basically just a mirror of the title
- [ ]  Entire files should be used, not just partial code snippets
- [ ]  Directory structure is incorrect. Visit Project Structure section in following wiki: 

https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles

**What you'll learn?**
- [ ] This section should be expanded. Perhaps include what Arquillian is and the advantages/importance that it has.

**Try what you'll build**
- [ ]  Have the maven command and gradle command in 2 separate code blocks
* gradle build doesn't work for me (same issue as: https://github.com/OpenLiberty/draft-guide-arquillian-managed/issues/2)

**Configuring your test build**
- [ ]  "You can learn more about the Arquillian Liberty dependency bundles _here_."  instead of hyperlinking here, hyperlink the title of where the link is taking users (Arquillian Liberty Dependencies repository.)

Likewise for the other 4 times it is used (twice more in using Maven section, 2 times in using gradle section)
- [ ] Is there a reason that the maven liberty plugin version is defined in the following way: "[17.0.0.4,)"? The other guides tend to use "RELEASE".

**Configuring the server.xml**
- [ ]  Entire file should be placed here. Instead of telling the user to add a particular feature.

**Adding your Arquillian test**
- [ ] "Create the test file at src/test/java/org/arquillian/example/GreeterIT.java" -> "Create the src/test/java/org/arquillian/example/GreeterIT.java test file."
- [ ]  "The contents of the file are reproduced below. A detailed explanation follows." Not sure if these sentences are actually necessary. 
- [ ]  According to https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles, should have separate variables for expected and actual defined when using assertEquals() method.

**Comment by evelinec** [comment]
@andrewdes while you reviewing the latest guide, can you verify that the issues you raised here are addressed? If not, point those out. Thanks.

**Comment by andrewdes** [comment]
@evelinec the feedback above that is still relevant and has not been changed will be reflected in the points listed here: https://github.com/OpenLiberty/draft-guide-arquillian-managed/issues/16
