### ISSUE TITLE
Pre-Publishing Tests 

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-arquillian-managed#49]
Pre-Publishing Tests

- [x] Check appearance (contents, headings, paragraphs, code snippets, outputs, links, hotspots) of the guide on test site, ie, qa-guides
- [x] Read through the guide 
- [x] Clone repo and test finish directory with no error
- [x] Run `diff -r start/ finish/` 
- [x] Follow the instruction in the guide to test that it is working
- Use the `copy` buttons instead of typing 
- [x] Check that the release date on the readme.adoc is the publishing date

**Comment by andrewdes** [comment]
Pre-Publishing Tests

- [ ] Check appearance (contents, headings, paragraphs, code snippets, outputs, links, hotspots) of the guide on test site, ie, qa-guides
- [ ] Read through the guide 
- [ ] Clone repo and test finish directory with no error
- [ ] Run `diff -r start/ finish/` 
- [ ] Follow the instruction in the guide to test that it is working
- [ ] Use the `copy` buttons instead of typing 
- [ ] Check that the release date on the readme.adoc is the publishing date

----

- [ ] "The arquillian-managed path in the URL comes from the WAR name you specified when you created the web archive in the `@Deployment` method." 

I don't like referring to the method as the `@Deployment` method. Perhaps: "`@Deployment` **annotated** method" or "`createDeployment()` method"

- [ ] "This test case calls the listContents() method to get all systems are stored in this inventory and verifies that one system is found and it’s localhost" -> I think this sentence should be reworded, I find it to be confusing. Perhaps something like: "This test case calls the listContents() method to get all the systems that are stored in the inventory and verifies that localhost is the only system that is found." or something similar

- [ ]  "The sequence is important for the two tests, as the results in the first test **impacts** the second one." -> The sequence is important for the two tests, as the results in the first test **impact** the second one.

- [ ] In the running the tests section, the test output should not be in a copyable box

**Comment by evelinec** [comment]
Addressed all feedback except for the test output. I checked both the libertydev and qa test sites, the test output isn't copyable.

**Comment by evelinec** [comment]
@andrewdes confirmed that there's no copy button for the test output. Closed.
